services:
  # See https://render.com/docs/blueprint-spec for more info on render blueprints
  - type: web
    name: trending_youtube_DASHboard
    env: python
    plan: free
    # A requirements.txt file must exist
    buildCommand: pip install -r src/requirements.txt
    # A src/app.py file must exist and contain `server=app.server`
    startCommand: gunicorn --chdir src app:server
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.6
